name: Django CI with Docker

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker image
      - name: Build Docker image
        run: docker build -t my-django-app .

      # Run Django tests inside container
      - name: Run migrations
        run: docker run --rm my-django-app python manage.py migrate

      - name: Run tests
        run: docker run --rm my-django-app python manage.py test


