name: Django CI (Local Test + Lint + Coverage)

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies + tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black coverage

      # Step 4: Run flake8 lint check
      - name: Lint with flake8
        run: |
          echo "Running flake8..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      # Step 5: Check code formatting with black
      - name: Check code formatting
        run: |
          echo "Checking code formatting with black..."
          black --check .

      # Step 6: Run migrations
      - name: Run migrations
        run: python manage.py migrate

      # Step 7: Run tests with coverage
      - name: Run tests with coverage
        run: |
          coverage run manage.py test
          coverage report


